sudo: required
language: dart
language: android
os:
- linux
jdk:
-  oraclejdk8
#

script:
- flutter build aot
- flutter build apk
- flutter build flx
#

before_install:
- git clone https://github.com/flutter/flutter.git
- wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
- unzip gradle-3.5-bin.zip
#

install:
- export GRADLE_HOME=$PWD/gradle-3.5
- export PATH=$GRADLE_HOME/bin:$PATH
- export PATH=./flutter/bin:$PATH
#

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - addon-google_apis-google-21